@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json


###

GET {{host}}/api/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZTA2MTVmYzUyODAwMjIxZDAyOTgiLCJpYXQiOjE2MjA3ODE3MzAsImV4cCI6MTYyMzM3MzczMH0.EX3Stt3Wmye1yUngR_3jDY9hpDYbJq_xC2haF89sDTI

###
POST {{host}}/api/expenses
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZTA2MTVmYzUyODAwMjIxZDAyOTgiLCJpYXQiOjE2MjA3ODE3MzAsImV4cCI6MTYyMzM3MzczMH0.EX3Stt3Wmye1yUngR_3jDY9hpDYbJq_xC2haF89sDTI

{
    "user": "6097532154f624a356576a4f",
    "title": "This is the first post",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    "amount": 2000,
    "status": true
}

###
GET {{host}}/api/expenses/6097d8ed4a0952b4e14386f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZTA2MTVmYzUyODAwMjIxZDAyOTgiLCJpYXQiOjE2MjA3ODE3MzAsImV4cCI6MTYyMzM3MzczMH0.EX3Stt3Wmye1yUngR_3jDY9hpDYbJq_xC2haF89sDTI

###
PUT {{host}}/api/expenses/6097d7fc4a0952b4e14386e9
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZDUzNmZlM2M0OWIzZmI1NTc4NWUiLCJpYXQiOjE2MjA1NjMzNjEsImV4cCI6MTYyMzE1NTM2MX0.UoSBmxQqpdjLYsILlWPO9iv9E12tzUFMUglQZeCo0S8

{
    "user": "6097532154f624a356576a4f",
    "title": "This is the first post updated again",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    "amount": 2000,
    "status": true
}

###
DELETE {{host}}/api/expenses/6097d7fc4a0952b4e14386e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZDUzNmZlM2M0OWIzZmI1NTc4NWUiLCJpYXQiOjE2MjA1NjMzNjEsImV4cCI6MTYyMzE1NTM2MX0.UoSBmxQqpdjLYsILlWPO9iv9E12tzUFMUglQZeCo0S8

###
GET {{host}}/api/expenses/byDate?startDate=2021-05-04&endDate=2021-05-26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk3ZDUzNmZlM2M0OWIzZmI1NTc4NWUiLCJpYXQiOjE2MjA1NjMzNjEsImV4cCI6MTYyMzE1NTM2MX0.UoSBmxQqpdjLYsILlWPO9iv9E12tzUFMUglQZeCo0S8
